# Generated by Django 5.1.5 on 2025-01-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='Задача')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('checked', models.BooleanField(blank=True, verbose_name='Выполнено')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания таски')),
            ],
        ),
    ]
