# Generated by Django 5.1.5 on 2025-02-11 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='checked',
            field=models.BooleanField(blank=True, default=False, verbose_name='Выполнено'),
        ),
    ]
